mysql:
  dsn: "root:1238564@tcp(127.0.0.1:3306)/card?charset=utf8mb4&parseTime=True&loc=Local"


redis:
  addr: "localhost:6379"

etcd:
  endpoints:
    - "localhost:2379"

grpc:
  server:
    name: "card"
    weight: 100
    addr: ":50056"
    etcdTTL: 60